"""Еще одна попытка перемиграции после изменений

Revision ID: b343e50c4c1a
Revises: 92fdddd0c03c
Create Date: 2025-03-15 22:54:41.125060

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b343e50c4c1a"
down_revision: Union[str, None] = "92fdddd0c03c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
