"""Create otder nullable true

Revision ID: 92fdddd0c03c
Revises: 4b861d6e9719
Create Date: 2025-03-15 22:14:44.580445

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "92fdddd0c03c"
down_revision: Union[str, None] = "4b861d6e9719"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "status",
        existing_type=postgresql.ENUM(
            "pending",
            "in_progress",
            "completed",
            "canceled",
            name="orderstatus",
        ),
        nullable=True,
        existing_server_default=sa.text("'pending'::orderstatus"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "status",
        existing_type=postgresql.ENUM(
            "pending",
            "in_progress",
            "completed",
            "canceled",
            name="orderstatus",
        ),
        nullable=False,
        existing_server_default=sa.text("'pending'::orderstatus"),
    )
    # ### end Alembic commands ###
