"""Modified int to bigint

Revision ID: 3e911004a6ac
Revises: 3057d1616d62
Create Date: 2025-03-19 20:02:38.736345

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3e911004a6ac"
down_revision: Union[str, None] = "3057d1616d62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELED",
                name="orderstatus",
            ),
            nullable=False,
        ),
    )
    op.drop_column("orders", "status_new")
    op.alter_column(
        "users",
        "telegram_id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(always=False),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "telegram_id",
        existing_type=sa.BigInteger(),
        server_default=None,
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.add_column(
        "orders",
        sa.Column(
            "status_new",
            postgresql.ENUM(
                "В_ожидании",
                "В_прогрессе",
                "Выполнен",
                "Отменен",
                name="orderstatus",
            ),
            server_default=sa.text("'В_ожидании'::orderstatus"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("orders", "status")
    # ### end Alembic commands ###
